// Generated by jextract

package org.purejava.winsparkle;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _timespec32 {
 *     __time32_t tv_sec;
 *     long tv_nsec;
 * }
 * }
 */
public class _timespec32 {

    _timespec32() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        winsparkle_h.C_LONG.withName("tv_sec"),
        winsparkle_h.C_LONG.withName("tv_nsec")
    ).withName("_timespec32");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt tv_sec$LAYOUT = (OfInt)$LAYOUT.select(groupElement("tv_sec"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __time32_t tv_sec
     * }
     */
    public static final OfInt tv_sec$layout() {
        return tv_sec$LAYOUT;
    }

    private static final long tv_sec$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __time32_t tv_sec
     * }
     */
    public static final long tv_sec$offset() {
        return tv_sec$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __time32_t tv_sec
     * }
     */
    public static int tv_sec(MemorySegment struct) {
        return struct.get(tv_sec$LAYOUT, tv_sec$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __time32_t tv_sec
     * }
     */
    public static void tv_sec(MemorySegment struct, int fieldValue) {
        struct.set(tv_sec$LAYOUT, tv_sec$OFFSET, fieldValue);
    }

    private static final OfInt tv_nsec$LAYOUT = (OfInt)$LAYOUT.select(groupElement("tv_nsec"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long tv_nsec
     * }
     */
    public static final OfInt tv_nsec$layout() {
        return tv_nsec$LAYOUT;
    }

    private static final long tv_nsec$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long tv_nsec
     * }
     */
    public static final long tv_nsec$offset() {
        return tv_nsec$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long tv_nsec
     * }
     */
    public static int tv_nsec(MemorySegment struct) {
        return struct.get(tv_nsec$LAYOUT, tv_nsec$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long tv_nsec
     * }
     */
    public static void tv_nsec(MemorySegment struct, int fieldValue) {
        struct.set(tv_nsec$LAYOUT, tv_nsec$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

