// Generated by jextract

package org.purejava.winsparkle;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;
class constants$11 {

    static final FunctionDescriptor win_sparkle_did_not_find_update_callback_t$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle win_sparkle_did_not_find_update_callback_t$MH = RuntimeHelper.downcallHandle(
        constants$11.win_sparkle_did_not_find_update_callback_t$FUNC
    );
    static final FunctionDescriptor win_sparkle_set_did_not_find_update_callback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle win_sparkle_set_did_not_find_update_callback$MH = RuntimeHelper.downcallHandle(
        "win_sparkle_set_did_not_find_update_callback",
        constants$11.win_sparkle_set_did_not_find_update_callback$FUNC
    );
    static final FunctionDescriptor win_sparkle_update_cancelled_callback_t$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle win_sparkle_update_cancelled_callback_t$MH = RuntimeHelper.downcallHandle(
        constants$11.win_sparkle_update_cancelled_callback_t$FUNC
    );
    static final FunctionDescriptor win_sparkle_set_update_cancelled_callback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle win_sparkle_set_update_cancelled_callback$MH = RuntimeHelper.downcallHandle(
        "win_sparkle_set_update_cancelled_callback",
        constants$11.win_sparkle_set_update_cancelled_callback$FUNC
    );
    static final FunctionDescriptor win_sparkle_update_skipped_callback_t$FUNC = FunctionDescriptor.ofVoid();
}


