// Generated by jextract

package org.purejava.winsparkle;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;
class constants$13 {

    static final FunctionDescriptor win_sparkle_update_dismissed_callback_t$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle win_sparkle_update_dismissed_callback_t$MH = RuntimeHelper.downcallHandle(
        constants$13.win_sparkle_update_dismissed_callback_t$FUNC
    );
    static final FunctionDescriptor win_sparkle_set_update_dismissed_callback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle win_sparkle_set_update_dismissed_callback$MH = RuntimeHelper.downcallHandle(
        "win_sparkle_set_update_dismissed_callback",
        constants$13.win_sparkle_set_update_dismissed_callback$FUNC
    );
    static final FunctionDescriptor win_sparkle_user_run_installer_callback_t$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle win_sparkle_user_run_installer_callback_t$MH = RuntimeHelper.downcallHandle(
        constants$13.win_sparkle_user_run_installer_callback_t$FUNC
    );
    static final FunctionDescriptor win_sparkle_set_user_run_installer_callback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle win_sparkle_set_user_run_installer_callback$MH = RuntimeHelper.downcallHandle(
        "win_sparkle_set_user_run_installer_callback",
        constants$13.win_sparkle_set_user_run_installer_callback$FUNC
    );
    static final FunctionDescriptor win_sparkle_check_update_with_ui$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle win_sparkle_check_update_with_ui$MH = RuntimeHelper.downcallHandleVariadic(
        "win_sparkle_check_update_with_ui",
        constants$13.win_sparkle_check_update_with_ui$FUNC
    );
}


