// Generated by jextract

package org.purejava.winsparkle;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;
class constants$10 {

    static final FunctionDescriptor win_sparkle_shutdown_request_callback_t$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle win_sparkle_shutdown_request_callback_t$MH = RuntimeHelper.downcallHandle(
        constants$10.win_sparkle_shutdown_request_callback_t$FUNC
    );
    static final FunctionDescriptor win_sparkle_set_shutdown_request_callback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle win_sparkle_set_shutdown_request_callback$MH = RuntimeHelper.downcallHandle(
        "win_sparkle_set_shutdown_request_callback",
        constants$10.win_sparkle_set_shutdown_request_callback$FUNC
    );
    static final FunctionDescriptor win_sparkle_did_find_update_callback_t$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle win_sparkle_did_find_update_callback_t$MH = RuntimeHelper.downcallHandle(
        constants$10.win_sparkle_did_find_update_callback_t$FUNC
    );
    static final FunctionDescriptor win_sparkle_set_did_find_update_callback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle win_sparkle_set_did_find_update_callback$MH = RuntimeHelper.downcallHandle(
        "win_sparkle_set_did_find_update_callback",
        constants$10.win_sparkle_set_did_find_update_callback$FUNC
    );
    static final FunctionDescriptor win_sparkle_did_not_find_update_callback_t$FUNC = FunctionDescriptor.ofVoid();
}


