// Generated by jextract

package org.purejava.winsparkle;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;
class constants$7 {

    static final FunctionDescriptor win_sparkle_set_app_details$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle win_sparkle_set_app_details$MH = RuntimeHelper.downcallHandle(
        "win_sparkle_set_app_details",
        constants$7.win_sparkle_set_app_details$FUNC
    );
    static final FunctionDescriptor win_sparkle_set_app_build_version$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle win_sparkle_set_app_build_version$MH = RuntimeHelper.downcallHandle(
        "win_sparkle_set_app_build_version",
        constants$7.win_sparkle_set_app_build_version$FUNC
    );
    static final FunctionDescriptor win_sparkle_set_http_header$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle win_sparkle_set_http_header$MH = RuntimeHelper.downcallHandle(
        "win_sparkle_set_http_header",
        constants$7.win_sparkle_set_http_header$FUNC
    );
    static final FunctionDescriptor win_sparkle_clear_http_headers$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle win_sparkle_clear_http_headers$MH = RuntimeHelper.downcallHandleVariadic(
        "win_sparkle_clear_http_headers",
        constants$7.win_sparkle_clear_http_headers$FUNC
    );
    static final FunctionDescriptor win_sparkle_set_registry_path$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle win_sparkle_set_registry_path$MH = RuntimeHelper.downcallHandle(
        "win_sparkle_set_registry_path",
        constants$7.win_sparkle_set_registry_path$FUNC
    );
    static final FunctionDescriptor win_sparkle_set_config_methods$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle win_sparkle_set_config_methods$MH = RuntimeHelper.downcallHandle(
        "win_sparkle_set_config_methods",
        constants$7.win_sparkle_set_config_methods$FUNC
    );
}


