// Generated by jextract

package org.purejava.winsparkle;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;
class constants$9 {

    static final FunctionDescriptor win_sparkle_error_callback_t$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle win_sparkle_error_callback_t$MH = RuntimeHelper.downcallHandle(
        constants$9.win_sparkle_error_callback_t$FUNC
    );
    static final FunctionDescriptor win_sparkle_set_error_callback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle win_sparkle_set_error_callback$MH = RuntimeHelper.downcallHandle(
        "win_sparkle_set_error_callback",
        constants$9.win_sparkle_set_error_callback$FUNC
    );
    static final FunctionDescriptor win_sparkle_can_shutdown_callback_t$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle win_sparkle_can_shutdown_callback_t$MH = RuntimeHelper.downcallHandle(
        constants$9.win_sparkle_can_shutdown_callback_t$FUNC
    );
    static final FunctionDescriptor win_sparkle_set_can_shutdown_callback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle win_sparkle_set_can_shutdown_callback$MH = RuntimeHelper.downcallHandle(
        "win_sparkle_set_can_shutdown_callback",
        constants$9.win_sparkle_set_can_shutdown_callback$FUNC
    );
    static final FunctionDescriptor win_sparkle_shutdown_request_callback_t$FUNC = FunctionDescriptor.ofVoid();
}


