// Generated by jextract

package org.purejava.winsparkle;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct win_sparkle_config_methods_tag {
 *     int (*config_read)(const char *, wchar_t *, size_t, void *) __attribute__((cdecl));
 *     void (*config_write)(const char *, const wchar_t *, void *) __attribute__((cdecl));
 *     void (*config_delete)(const char *, void *) __attribute__((cdecl));
 *     void *user_data;
 * }
 * }
 */
public class win_sparkle_config_methods_tag {

    win_sparkle_config_methods_tag() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        winsparkle_h.C_POINTER.withName("config_read"),
        winsparkle_h.C_POINTER.withName("config_write"),
        winsparkle_h.C_POINTER.withName("config_delete"),
        winsparkle_h.C_POINTER.withName("user_data")
    ).withName("win_sparkle_config_methods_tag");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * {@snippet lang=c :
     * int (*config_read)(const char *, wchar_t *, size_t, void *) __attribute__((cdecl))
     * }
     */
    public static class config_read {

        config_read() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, long _x2, MemorySegment _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            winsparkle_h.C_INT,
            winsparkle_h.C_POINTER,
            winsparkle_h.C_POINTER,
            winsparkle_h.C_LONG_LONG,
            winsparkle_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = winsparkle_h.upcallHandle(config_read.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(config_read.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1, long _x2, MemorySegment _x3) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout config_read$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("config_read"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*config_read)(const char *, wchar_t *, size_t, void *) __attribute__((cdecl))
     * }
     */
    public static final AddressLayout config_read$layout() {
        return config_read$LAYOUT;
    }

    private static final long config_read$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*config_read)(const char *, wchar_t *, size_t, void *) __attribute__((cdecl))
     * }
     */
    public static final long config_read$offset() {
        return config_read$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*config_read)(const char *, wchar_t *, size_t, void *) __attribute__((cdecl))
     * }
     */
    public static MemorySegment config_read(MemorySegment struct) {
        return struct.get(config_read$LAYOUT, config_read$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*config_read)(const char *, wchar_t *, size_t, void *) __attribute__((cdecl))
     * }
     */
    public static void config_read(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(config_read$LAYOUT, config_read$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*config_write)(const char *, const wchar_t *, void *) __attribute__((cdecl))
     * }
     */
    public static class config_write {

        config_write() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            winsparkle_h.C_POINTER,
            winsparkle_h.C_POINTER,
            winsparkle_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = winsparkle_h.upcallHandle(config_write.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(config_write.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout config_write$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("config_write"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*config_write)(const char *, const wchar_t *, void *) __attribute__((cdecl))
     * }
     */
    public static final AddressLayout config_write$layout() {
        return config_write$LAYOUT;
    }

    private static final long config_write$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*config_write)(const char *, const wchar_t *, void *) __attribute__((cdecl))
     * }
     */
    public static final long config_write$offset() {
        return config_write$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*config_write)(const char *, const wchar_t *, void *) __attribute__((cdecl))
     * }
     */
    public static MemorySegment config_write(MemorySegment struct) {
        return struct.get(config_write$LAYOUT, config_write$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*config_write)(const char *, const wchar_t *, void *) __attribute__((cdecl))
     * }
     */
    public static void config_write(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(config_write$LAYOUT, config_write$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*config_delete)(const char *, void *) __attribute__((cdecl))
     * }
     */
    public static class config_delete {

        config_delete() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            winsparkle_h.C_POINTER,
            winsparkle_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = winsparkle_h.upcallHandle(config_delete.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(config_delete.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout config_delete$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("config_delete"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*config_delete)(const char *, void *) __attribute__((cdecl))
     * }
     */
    public static final AddressLayout config_delete$layout() {
        return config_delete$LAYOUT;
    }

    private static final long config_delete$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*config_delete)(const char *, void *) __attribute__((cdecl))
     * }
     */
    public static final long config_delete$offset() {
        return config_delete$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*config_delete)(const char *, void *) __attribute__((cdecl))
     * }
     */
    public static MemorySegment config_delete(MemorySegment struct) {
        return struct.get(config_delete$LAYOUT, config_delete$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*config_delete)(const char *, void *) __attribute__((cdecl))
     * }
     */
    public static void config_delete(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(config_delete$LAYOUT, config_delete$OFFSET, fieldValue);
    }

    private static final AddressLayout user_data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("user_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static final AddressLayout user_data$layout() {
        return user_data$LAYOUT;
    }

    private static final long user_data$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static final long user_data$offset() {
        return user_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static MemorySegment user_data(MemorySegment struct) {
        return struct.get(user_data$LAYOUT, user_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static void user_data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(user_data$LAYOUT, user_data$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

