// Generated by jextract

package org.purejava.winsparkle;

import java.lang.foreign.Addressable;
import java.lang.foreign.MemoryAddress;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.MemorySession;
public interface win_sparkle_user_run_installer_callback_t {

    int apply(java.lang.foreign.MemoryAddress _x0);
    static MemorySegment allocate(win_sparkle_user_run_installer_callback_t fi, MemorySession session) {
        return RuntimeHelper.upcallStub(win_sparkle_user_run_installer_callback_t.class, fi, constants$13.win_sparkle_user_run_installer_callback_t$FUNC, session);
    }
    static win_sparkle_user_run_installer_callback_t ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress __x0) -> {
            try {
                return (int)constants$13.win_sparkle_user_run_installer_callback_t$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)__x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


