// Generated by jextract

package org.purejava.windows;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemoryAddress;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
class constants$14 {

    static final FunctionDescriptor win_sparkle_check_update_with_ui_and_install$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle win_sparkle_check_update_with_ui_and_install$MH = RuntimeHelper.downcallHandleVariadic(
        "win_sparkle_check_update_with_ui_and_install",
        constants$14.win_sparkle_check_update_with_ui_and_install$FUNC
    );
    static final FunctionDescriptor win_sparkle_check_update_without_ui$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle win_sparkle_check_update_without_ui$MH = RuntimeHelper.downcallHandleVariadic(
        "win_sparkle_check_update_without_ui",
        constants$14.win_sparkle_check_update_without_ui$FUNC
    );
    static final MemoryAddress NULL$ADDR = MemoryAddress.ofLong(0L);
    static final MemorySegment WIN_SPARKLE_VERSION_STRING$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("0.7.0");
}


