// Generated by jextract

package org.purejava.windows;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;
class constants$12 {

    static final FunctionDescriptor win_sparkle_update_skipped_callback_t$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle win_sparkle_update_skipped_callback_t$MH = RuntimeHelper.downcallHandle(
        constants$12.win_sparkle_update_skipped_callback_t$FUNC
    );
    static final FunctionDescriptor win_sparkle_set_update_skipped_callback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle win_sparkle_set_update_skipped_callback$MH = RuntimeHelper.downcallHandle(
        "win_sparkle_set_update_skipped_callback",
        constants$12.win_sparkle_set_update_skipped_callback$FUNC
    );
    static final FunctionDescriptor win_sparkle_update_postponed_callback_t$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle win_sparkle_update_postponed_callback_t$MH = RuntimeHelper.downcallHandle(
        constants$12.win_sparkle_update_postponed_callback_t$FUNC
    );
    static final FunctionDescriptor win_sparkle_set_update_postponed_callback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle win_sparkle_set_update_postponed_callback$MH = RuntimeHelper.downcallHandle(
        "win_sparkle_set_update_postponed_callback",
        constants$12.win_sparkle_set_update_postponed_callback$FUNC
    );
    static final FunctionDescriptor win_sparkle_update_dismissed_callback_t$FUNC = FunctionDescriptor.ofVoid();
}


